# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

  ExportData.classes.csv_generator:
          class: ExportDataBundle\Classes\GenerateCsv
          arguments: ["@doctrine.orm.entity_manager","%kernel.default_locale%"]
          public: true