<?php

namespace ExportDataBundle\Repository;

/**
 * StudentAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentAddressRepository extends \Doctrine\ORM\EntityRepository
{
}
