<?php

namespace MerchantTransactionsBundle\Repository;

/**
 * MerchantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MerchantsRepository extends \Doctrine\ORM\EntityRepository
{
}
